title: QA-Stions?
subtitle: Comunidad QA
description: >- # this means to ignore newlines until "baseurl:"
  Podcast sobre el mundo QA ¿Te gustaría participar? Escribe a qastions.info@gmail.com y cuéntanos de qué te gustaría hablar!

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Sobre QA-Stions?
      url: /about
    - text: Blog
      url: /blog
    - text: Galería
      url: /gallery
    - text: Contactar
      url : /contact

# Edit these details

author_logo: QA-Stions-Square.png
author: Jesús Pajares
author_bio: Any QA-Stions?
author_email: "qastions.info@gmail.com"
author_location: Granada

# social links
twitter_username: qastions
github_username:  QAStions
linkedin_username: company/qa-stions

# formspree (contact form)
formspree_email: qastions.info@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
#collections:
# - products

# Gallery
#defaults:
#  -
#    scope:
#      path: "gallery"
 #   values:
 #     permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
